SELECT DISTINCT
  MARKETCLUSTER AS MARKET,
  MARKET AS SUBMARKET,
  EUTRANCELL_NAME

FROM PDW_MOBILITYSCORECARD_VIEWS.LTE_RTB_SCORECARD_DY
WHERE 
  EUCELLVENDORLIST = 'E' AND MARKET <> '*' AND MARKET <> '*COMMERCIAL' 
  AND MARKET <> '-' AND MARKET NOT LIKE '%-PART' AND EUTRANCELL_NAME <> '*' 
  AND DATETIMELOCAL >= '{start_date}'